name: "Unit tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          extensions: "ctype, curl, date, dom, imagick, intl, json, libxml, mbstring, Reflection, session, SimpleXML, xsl, zlib"
          tools: composer

      - name: "Install dependencies"
        run: "composer update --ansi --no-interaction --no-progress"

      - name: "Run phpunit"
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.1
          #php_extensions: ctype curl date dom imagick intl json libxml mbstring Reflection session SimpleXML xdebug xsl zlib
          php_extensions: ctype curl date dom imagick intl json libxml mbstring Reflection session SimpleXML xsl zlib
          configuration: build/phpunit.xml
          args: --no-coverage
        #env:
          #XDEBUG_MODE: coverage